version: "3.8"

services:
    postgres:
        image: postgres:16
        container_name: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - ~/pgdata:/var/lib/postgresql/data

    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: leo-web-api
        ports:
            - "${API_PORT}:${API_PORT}"
        volumes:
            - .:/app
        environment:
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_USER: ${POSTGRES_USER}
            DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
            DATABASE_NAME: ${POSTGRES_DB}
        depends_on:
            - postgres

volumes:
    pgdata:
